### ISSUE TITLE
enverus_developer_api.DAQueryException: invalid column names in query parameters: [wellname]

### ISSUE THREAD

**Issue by kttii** [enverus-ea/enverus-developer-api#30]
I am trying to do a query by wellname but it is returning an error that 'wellname' is invalid (but it works on other fields)

# this works
for row in v3.query('wells', deleteddate='null', county='REEVES', API_UWI_14_Unformatted='42389336070000', fields='API_UWI_14_Unformatted,WellName'): 
    print(row)

# this works
for row in v3.query('wells', deleteddate='null', county='REEVES', ENVOperator='VTX ENERGY OPERATING LLC', fields='API_UWI_14_Unformatted,WellName'): 
    print(row)

# produces invalid column name error
for row in v3.query('wells', deleteddate='null', WellName='BONGO 13 3', fields='API_UWI_14_Unformatted,WellName'): 
    print(row)

#result
Traceback (most recent call last):
  File "C:\Users\TThompson\Documents\Total_Svy_Export\Total_Svy_Export.py", line 41, in <module>
    for row in v3.query('wells', deleteddate='null', WellName='BONGO 13 3', fields='API_UWI_14_Unformatted,WellName'): 
  File "C:\Users\TThompson\AppData\Local\Programs\Python\Python310\lib\site-packages\enverus_developer_api\__init__.py", line 684, in query
    response = self.session.get(query_url, params=options, headers=request_headers)
  File "C:\Users\TThompson\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\TThompson\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\TThompson\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "C:\Users\TThompson\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "C:\Users\TThompson\AppData\Local\Programs\Python\Python310\lib\site-packages\enverus_developer_api\__init__.py", line 160, in _check_response
    raise DAQueryException(response.text)
enverus_developer_api.DAQueryException: invalid column names in query parameters: [wellname]

**Comment by jra8927** [comment]
The reason for this error is because the column wellname is not setup as a filter. This column cant be used as a filter.
